[package]
name = "rustmo-server"
version = "0.1.1"
authors = ["Eric B. Ridge <eebbrr@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Talk to your code with Rustmo via Alexa"
homepage = "https://github.com/eeeebbbbrrrr/rustmo"
documentation = "https://github.com/eeeebbbbrrrr/rustmo"
repository = "https://github.com/eeeebbbbrrrr/rustmo"
readme = "../README.md"

[dependencies]
net2 = "0.2.33"
uuid = { version="0.8.1", features = ["v4"] }
reqwest = "0.9.22"
regex = "1.3.1"
hyper = "0.10.13"
rayon = "1.2.1"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
serde-xml-rs = "0.3.1"